#!/bin/sh

GAME="$1"
RECFILE="$2"
shift;shift

mv "$HOME/.mame/cfg/$GAME.cfg"{,~} 2> /dev/null
mv "$HOME/.mame/diff/$GAME.dif"{,~} 2> /dev/null

./mame "$GAME" -playback "$RECFILE.inp" -noplugin hiscore -nvram_directory /dev/null "$@"

mv "$HOME/.mame/cfg/$GAME.cfg"{~,} 2> /dev/null
mv "$HOME/.mame/diff/$GAME.dif"{~,} 2> /dev/null
